---
version: "3.9"

services:
  web:
    image: "wydler/mta-sts-web"
    container_name: "mta-sts_webserver"
    restart: "unless-stopped"
    ports:
      - "80:80"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      - "./data/nginx/logs:/var/log/nginx:rw"
      - "./data/webapp:/var/www/html/mta-sts:ro"
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw"
    links:
      - app
    networks:
      frontend:


  app:
    image: "wydler/mta-sts-uwsgi"
    container_name: "mta-sts_application"
    restart: "unless-stopped"
    user: "33:33"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      - "./data/webapp:/var/www/html/mta-sts:ro"
      - "./conf/uwsgi/mta-sts.ini:/etc/uwsgi/vassals/mta-sts.ini:ro"
      - "./conf/uwsgi/emperor.ini:/etc/uwsgi/apps-enabled/emperor.ini:ro"
    networks:
      frontend:


networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:face:cafe:feed::/64

